appName: account-service

image:
  name: jstjerne/account-service
  tag: latest

namespace: default

configmap:
  name: myappconfigmapv0.1
  data:
    CUSTOM_HEADER: "This app was deployed with Helm!"
