apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: devops-application
    namespace: default
spec:
    project: default
    source:
        repoURL: https://github.com/JonasStjerne/devops.git
        targetRevision: HEAD
        path: helm/charts/account-service
    destination:
        server: https://kubernetes.default.svc
        namespace: devops-app

    syncPolicy:
        syncOptions:
            - CreateNamespace=true

        automated:
            selfHeal: true
            prune: true
