name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service:
          - auth-service
    
    steps:
      - name: Determine Changed Files
        id:  changed-files
        run: echo "changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^${{ matrix.service }}/.*' || true)" >> $GITHUB_OUTPUT
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ matrix.service }}"
          push: true
          tags: jstjerne/${{ matrix.service }}:latest
